name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o deploy --no-build
    - name: Copy via SSH
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "/home/runner/work/restaurant-api/restaurant-api/deploy/"
        remote: "/var/www/restaurant-api/"
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY}}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
    - name: Restart service via SSH
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: service restaurant-api restart
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY}}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
